### ISSUE TITLE
potential colour scheme

### ISSUE THREAD

**Issue by adrian-activate** [ActivateMedia/DCAF-Ukraine#1]
![palette5649e75a08f86](https://cloud.githubusercontent.com/assets/5072273/11184171/0ae49d50-8c6e-11e5-9060-e0098504004c.png)

**Comment by adrian-activate** [comment]
@karinapriajina what do you think?

**Comment by karinapriajina** [comment]
What are these for exactly?

**Comment by adrian-activate** [comment]
These could be the colours used for the site. Backgrounds, text, links etc.

It might be you need to see in in situ before you decide if you like it or not.
