### ISSUE TITLE
Related Keyword hotlinker

### ISSUE THREAD

**Issue by adrian-activate** [ActivateMedia/DCAF-Ukraine#11]
Need to find a plugin to hot link words in pages to topic/ factsheet pages.

(wikipedia style)

**Comment by andreafalzetti** [comment]
The WordPress Plugin: [SEO Smart Links](https://wordpress.org/plugins/seo-automatic-links/) seems to do this, but he doesn't have great reviews and it might come with a bunch of features we don't need and probably limits on the keywords we want to use (I think we want to use the custom taxonomy terms like Topics - and the plugin might not support it).. I didn't find any better plugin out there.

This is a snippet of code that I've wrote in few minutes:

```
 function keywords_to_hyperlink( $content ) { 
    $categories = get_terms( 'category', 'orderby=count&hide_empty=0' );
    foreach($categories as $category) {
        $term_link = get_term_link($category);
        $content = preg_replace("/".$category->name."/i", "<a href=\"".$term_link."\">$0</a>", $content);
    }    

    return $content;
}
add_filter( 'the_content', 'keywords_to_hyperlink' ); 
```

And this is the output:

## I have created 3 categories (we can use any source in the DB or fix an array of keywords):

![screen shot 2015-12-14 at 11 47 26](https://cloud.githubusercontent.com/assets/2318450/11780274/a86413e4-a258-11e5-94ea-323de5029554.jpg)

## Without the snippet

![screen shot 2015-12-14 at 11 48 41](https://cloud.githubusercontent.com/assets/2318450/11780276/a869f05c-a258-11e5-9bb5-15963998487c.jpg)

## With this code in place:

![screen shot 2015-12-14 at 11 48 27](https://cloud.githubusercontent.com/assets/2318450/11780275/a8696b14-a258-11e5-9a6c-e6854ce63c9e.jpg)

I think we should just improve this a little bit without using any plugin. 

Just as a note, here there's a jQuery snippet that does the same but client-side:
http://jsfiddle.net/andrewwhitaker/VmHjJ/

**Comment by andreafalzetti** [comment]
I've created a plugin for DCAF Ukraine located in _wp-content/plugins/dcaf_ which contains the keyword-hotlinker component.

It's triggered by the [**the_content** hook](https://codex.wordpress.org/Plugin_API/Hooks_2.0.x). 

Please let me know if you need to add other hooks to activate the hotlinker in other sections/pages.
