### ISSUE TITLE
Set up google analytics

### ISSUE THREAD

**Issue by adrian-activate** [ActivateMedia/DCAF-Ukraine#13]
Just a reminder

**Comment by bhavesh-activatemedia** [comment]
Andrea to contact Cecil regarding getting access to the DCAF GA

**Comment by andreafalzetti** [comment]
I've set up a Google Analytics and Google Webmaster tool account for this site. @karinapriajina what's your Google email address so I can give you admin access to them?

**Comment by karinapriajina** [comment]
Thank you Andrea! I will set up a gmail and google account for the division now and let you know

**Comment by karinapriajina** [comment]
the address is: dcafddo@gmail.com

**Comment by andreafalzetti** [comment]
Great! I have invited you to the G Analytics account.

**Comment by karinapriajina** [comment]
Cool! One question: so to login I use the gmail and what password?

**Comment by andreafalzetti** [comment]
Yes, just open analytics.google.com/analytics/web/ and sign in with your gmail account.

**Comment by karinapriajina** [comment]
ah oki Thanks!

**Comment by bhavesh-activatemedia** [comment]
@andreafalzetti to send @karinapriajina tutorials explaining SEO

**Comment by andreafalzetti** [comment]
@karinapriajina I suggest you this one, it seems well done and more important it's recent so it should be aligned to the latest version of the Google Analytics interface.

[![IMAGE ALT TEXT](http://i3.ytimg.com/vi/gLjeIFukhyE/hqdefault.jpg)](http://www.youtube.com/watch?v=YOUTUBE_VIDEO_ID_HERE)

Alternatives:
- [Other Google Analytics videos on YouTube](https://www.youtube.com/results?search_query=google+analytics+2016)
- [Udemy Courses on Google Analytics](https://www.udemy.com/courses/search/?q=google+analytics&src=sac&kw=google+analytics&lang=en)

**Comment by bhavesh-activatemedia** [comment]
@andreafalzetti Has analytics been added to the site?

**Comment by andreafalzetti** [comment]
@bhavesh-activatemedia yes
