### ISSUE TITLE
Related content module

### ISSUE THREAD

**Issue by adrian-activate** [ActivateMedia/DCAF-Ukraine#14]
A module that lists any related content in the site on any any of the 5 content type pages -
- news
- publications
- events/confereces
- institutions
- fact sheets

The type of content in the listing will be indicated by a colour scheme and the an icon.

**Comment by andreafalzetti** [comment]
I have created a related content shortcode.

The plugin _DCAF_ that you will see in the backend is a wrapper for custom code (such as Widgets, Shortcodes, etc).

This functionality is located in _/wp-content/plugins/dcaf/**related_content**_.

The related content shortcode can be used as a standard shortcode. There's a parameter that defines the maximum number of posts displayed. The default value is 10.

```
In the CMS => [dcaf_related_content numberposts="5"]
In the Theme => <?php echo do_shortcode('[dcaf_related_content numberposts="5"]'); ?>
```

I've placed the shortcode in /theme/dcaf/**single.php**
