### ISSUE TITLE
Website Logo

### ISSUE THREAD

**Issue by activate-siva** [ActivateMedia/DCAF-Ukraine#15]

**Comment by karinapriajina** [comment]
![copy of logo_dcaf english hr](https://cloud.githubusercontent.com/assets/15872221/11210848/57e9d7ce-8d2b-11e5-9434-1cf925bed048.jpg)
![copy of logo_dcaf english -01](https://cloud.githubusercontent.com/assets/15872221/11210851/5c41b238-8d2b-11e5-8afe-02fe3d00e99f.jpg)

**Comment by activate-siva** [comment]
Thanks @karinapriajina

**Comment by karinapriajina** [comment]
We have another logo (a few versions of it). There's still one missing, the one from Razumkov centre. I will forward it as soon as we receive it.
![ro_bz_logo_1_rgb_diap_en](https://cloud.githubusercontent.com/assets/15872221/11496652/a0e66396-9813-11e5-9c6c-9f2d4e2ffd51.png)
![ro_bz_logo_1_rgb_pos_en](https://cloud.githubusercontent.com/assets/15872221/11496650/a0e43aa8-9813-11e5-8d50-78305b776668.png)
![ro_bz_logo_2_rgb_pos_en](https://cloud.githubusercontent.com/assets/15872221/11496653/a0ef4d76-9813-11e5-8118-099aecad59e2.png)
![ro_bz_logo_6_rgb_diap_en](https://cloud.githubusercontent.com/assets/15872221/11496651/a0e46910-9813-11e5-910f-4e27e74db746.png)
![ro_bz_logo_6_rgb_pos_en](https://cloud.githubusercontent.com/assets/15872221/11496648/a0e3dec8-9813-11e5-92e9-ea3e5151c340.png)
![ro_logo_2_rgb_pos op kleur_x_en](https://cloud.githubusercontent.com/assets/15872221/11496649/a0e431f2-9813-11e5-9c4f-0affebaf8a81.png)

**Comment by adrian-activate** [comment]
@karinapriajina the logos you are providing here. These are all for the footer?

Will there be a logo for the site?

**Comment by karinapriajina** [comment]
Hi there! Yes, these are for the footer. There will be no logo of the site, just a title. You can see it in the Word document I attached.
[Home page look.docx](https://github.com/ActivateMedia/DCAF-Ukraine/files/48283/Home.page.look.docx)

**Comment by karinapriajina** [comment]
[logo_razumk.pdf](https://github.com/ActivateMedia/DCAF-Ukraine/files/53926/logo_razumk.pdf)
[logo_Razumkov.pdf](https://github.com/ActivateMedia/DCAF-Ukraine/files/53927/logo_Razumkov.pdf)
![dcaf-logo-transparent-white for dark background](https://cloud.githubusercontent.com/assets/15872221/11627196/fbd2d80a-9ce8-11e5-9c68-c061fffb28bc.png)
![logo_dcaf english white for dark background](https://cloud.githubusercontent.com/assets/15872221/11627198/0055eff2-9ce9-11e5-89f8-6625c5542676.png)

**Comment by adrian-activate** [comment]
![logo_razumkov](https://cloud.githubusercontent.com/assets/5072273/12234654/6fa678ca-b866-11e5-94a8-43e3a5b9fa89.png)

**Comment by karinapriajina** [comment]
Hi everyone! Questions: is there a way of making all the logos the same size? Preferably smaller :) Many thanks!
