### ISSUE TITLE
Opinion polls page

### ISSUE THREAD

**Issue by adrian-activate** [ActivateMedia/DCAF-Ukraine#20]

**Comment by adrian-activate** [comment]
Can we discuss what this is @karinapriajina

**Comment by karinapriajina** [comment]
Hi Adrian! Yes of course, these are opinion polls that are going to be undertaken by one of our partners and the results, subsequent reports, publications and data will be published here. 
This is not related to the web stats or visitors if that's what you're thinking :-)

**Comment by adrian-activate** [comment]
How will you present this? All in one page?

**Comment by karinapriajina** [comment]
I haven't though about that to be honest. Probably one page, yes, as there are not many programmed for the time being and we don't want it to look too empty. So yep, one page will do.
