### ISSUE TITLE
Page 404

### ISSUE THREAD

**Issue by andreafalzetti** [ActivateMedia/DCAF-Ukraine#21]
It needs some work

http://dcaf-ua.activatemedia.com/hello

**Comment by andreafalzetti** [comment]
I've created the **404.php** file in the template (duplicated of page.php but without sidebar). There is a new LESS file (404.less) that controls this page. I've aligned the container to the center but I'm not sure this follows the style & feeling of the rest of the website, so please feel free to change it.

Example
![screen shot 2015-12-23 at 11 09 17](https://cloud.githubusercontent.com/assets/2318450/11974612/10a93c2c-a966-11e5-98e9-8c62e7a47cf4.jpg)

**Comment by bhavesh-activatemedia** [comment]
Action some CSS styling changes

**Comment by andreafalzetti** [comment]
This has been done
