### ISSUE TITLE
Links to social media accounts

### ISSUE THREAD

**Issue by adrian-activate** [ActivateMedia/DCAF-Ukraine#24]
add to footer

**Comment by adrian-activate** [comment]
@karinapriajina too send us url links

**Comment by karinapriajina** [comment]
https://twitter.com/dcaf_ukraine

https://www.linkedin.com/in/dcafukraine

so far these are all we have, we are setting up a facebook page now. Will give you the link asap

**Comment by karinapriajina** [comment]
Facebook page: https://www.facebook.com/DCAF.Ukraine/

**Comment by bhavesh-activatemedia** [comment]
ensure these have been actioned on the footer

**Comment by andreafalzetti** [comment]
I've installed a widget that allow you to add multiple social channels so if you have any other, please just add the URL from the widget. I've set the provided ones.

Path: `Appearance > Footer Widget 4 > Social Icons`

![screen shot 2016-08-16 at 14 37 54](https://cloud.githubusercontent.com/assets/2318450/17700784/1a62ef24-63bf-11e6-8fc1-7c2777d085ff.jpg)

**Comment by karinapriajina** [comment]
Thanks a lot!
