### ISSUE TITLE
Fix problems with content stream

### ISSUE THREAD

**Issue by adrian-activate** [ActivateMedia/DCAF-Ukraine#26]
![image](https://cloud.githubusercontent.com/assets/5072273/12234997/a151398a-b868-11e5-8aec-75e689b5a83d.png)

**Comment by adrian-activate** [comment]
![image](https://cloud.githubusercontent.com/assets/5072273/12235016/bb8e0918-b868-11e5-8438-f79e21e68f5f.png)

**Comment by activate-siva** [comment]
Done.
