### ISSUE TITLE
Home Page Template

### ISSUE THREAD

**Issue by adrian-activate** [ActivateMedia/DCAF-Ukraine#3]
The homepage consist of -
- Word cloud to link to fact sheets #2 
- Highlights section - this will show featured news, events, publications 
- Mega menu 
- footer bar

**Comment by adrian-activate** [comment]
@karinapriajina this is the basic wireframe layout we created while discussing your project.

![img_2610](https://cloud.githubusercontent.com/assets/5072273/11185418/99149da4-8c74-11e5-9e14-2cb94332d20e.png)

**Comment by adrian-activate** [comment]
From @karinapriajina : Just a few notes and questions from our side: I have added and changed a few items in the menu; we have a new web-title (check it out in the word doc below); we have decided that there is going to be a newsletter, therefore, the corresponding section in the footer of the web is to be maintained (see word doc). As to questions: can we fill-in the pages content (about, topics, ectivities etc)soon?

[Home page look.docx](https://github.com/ActivateMedia/DCAF-Ukraine/files/48285/Home.page.look.docx)

**Comment by karinapriajina** [comment]
Hi there! Quick note on the feedback I got from Claudia and Eden on the Homepage look. I personally love it, but I admit they have a point, which is: it's a bit dark. Given that it is all about security and anti-corruption, black comes across as a bit ironic. So, I am currently looking for an alternative photo (even though we all like the one that is there) that might be a little more colourful. So maybe a little more colour and light is what we need in general. :)

**Comment by karinapriajina** [comment]
Hello again! I've remembered we had a  conversation about the colour before Christmas (i.e above). How is that evolving? Is there a way to use a different set of colours for the "dark" parts of the homepage. Something more colourful and/or brighter? Many thanks!
