### ISSUE TITLE
"Under Construction" launch

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#30]

**Comment by activate-siva** [comment]
Remove the flags and add notice at the footer on all pages.

**Comment by bhavesh-activatemedia** [comment]
Photo credit text to be added: Photo credit: Ivan Bandura (Flickr)
Link Flckr to: https://www.flickr.com/photos/mac_ivan/11295411965/

**Comment by andreafalzetti** [comment]
This has been done.

```
<div style="font-size: 14px;color: lightgray;position: absolute;bottom: 0;width: 95%;padding: 20px;">Photo credit: Ivan Bandura (<a style="font-size: 14px;color: lightgray;" target="_blank" href="https://www.flickr.com/photos/mac_ivan/11295411965/">Flickr</a>)</div>
```

**Comment by bhavesh-activatemedia** [comment]
@andreafalzetti to move the content area up

**Comment by andreafalzetti** [comment]
Done

![screen shot 2016-08-12 at 11 36 49](https://cloud.githubusercontent.com/assets/2318450/17620003/17e7972c-6081-11e6-9cf4-6e82acd5e4cd.jpg)
![screen shot 2016-08-12 at 11 37 00](https://cloud.githubusercontent.com/assets/2318450/17620004/17e865b2-6081-11e6-8e5e-3cee676a7979.jpg)
