### ISSUE TITLE
Publications thumbnails and publications section appearance

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#32]
-Publication thumbnails should feature the cover of the publication. Where should the cover picture be uploaded?
- The side menu in the publication section: delete or hide
- Remove/hide publications from the home page because the thumbnail does not fit with the rest of the posts' appearance. 
- Change publication thumbnails to make them look like the ones on marsad (http://www.marsad.eg/en/publication/ )

**Comment by bhavesh-activatemedia** [comment]
1. Publication thumbnail feature to be created. Added on listing page as well as inner page
2. Add side menu for publication section. Karina to advise.
3. Hide publications from the home page

**Comment by karinapriajina** [comment]
I don't remember if we discussed this, but this is just to remind that Publications should appear in the chronological order of their publication year. I can't seem to localise where to put the data relative to the publishing year when uploading. 

Also, all the pdf files should be visible in all languages, only the English version is currently displayed in the listing. 

Thanks a lot!

**Comment by andreafalzetti** [comment]
You can edit the Publishing date - By default it's the date of publishing the publication within WordPress but this value can be edited. The following screenshots come from marsad.eg - Where Publications are ordered chronologically (from the most recent to the oldest) as you said, so we can use the same approach in this project, I'd suggest.

### Front-End

![screen shot 2016-08-09 at 17 31 35](https://cloud.githubusercontent.com/assets/2318450/17524737/aca816a6-5e57-11e6-9d1b-f7fd644f9b8b.jpg)

### Back-End

![screen shot 2016-08-09 at 17 32 21](https://cloud.githubusercontent.com/assets/2318450/17524738/acb80872-5e57-11e6-97bc-c008ca36e2ad.jpg)

The day and month are not displayed in the front-end (they could if you wish) but more important they can be used to order publications that have been published on the same year.

**Comment by karinapriajina** [comment]
Excellent! Thank you Andrea!

**Comment by andreafalzetti** [comment]
@karinapriajina I made the publication item smaller in the listing so you should be able to see more than one at the time. Can you check from your screen and tell me if you want smaller or if it's ok? Thanks

**Comment by karinapriajina** [comment]
That looks good! That's fine by me, I may have to consult our team see what they think sometime this week. Should be fine though

**Comment by bhavesh-activatemedia** [comment]
Images are large here: http://dcaf-ua.activatemedia.com/topic/anti-corruption/building-integrity/

**Comment by bhavesh-activatemedia** [comment]
@andreafalzetti http://dcaf-ua.activatemedia.com/publication/
The title, text and social icons should be to the right of the image. They have moved to below the image. Can you revert.

**Comment by andreafalzetti** [comment]
Issue fixed. Somehow the settings of the Easy Social Share Settings have changed, probably due to a recent update.

**Comment by karinapriajina** [comment]
Many thanks for this! :)
