### ISSUE TITLE
Photo credit on the homepage

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#33]
The photo credit is missing from the homepage

**Comment by bhavesh-activatemedia** [comment]
Photo credit text to be added: Photo credit: Ivan Bandura (Flickr)
Link Flckr to: https://www.flickr.com/photos/mac_ivan/11295411965/

**Comment by andreafalzetti** [comment]
I've added this above the footer. Please review

**Comment by karinapriajina** [comment]
Many Thanks Andrea!
