### ISSUE TITLE
Web footer

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#34]
Web footer has gone missing

**Comment by bhavesh-activatemedia** [comment]
To be recovered

**Comment by bhavesh-activatemedia** [comment]
@karinapriajina Are these the three logos you would like?
![5c41b238-8d2b-11e5-8afe-02fe3d00e99f](https://cloud.githubusercontent.com/assets/5073275/17437895/374f8ac0-5b18-11e6-8037-5d4d0ecb1db1.jpg)
![6fa678ca-b866-11e5-94a8-43e3a5b9fa89](https://cloud.githubusercontent.com/assets/5073275/17437896/37508164-5b18-11e6-8487-771cd79952e3.png)
![a0ef4d76-9813-11e5-8118-099aecad59e2](https://cloud.githubusercontent.com/assets/5073275/17437894/374eee8a-5b18-11e6-9117-e32286a433e1.png)

**Comment by karinapriajina** [comment]
Yes these are the ones. You have a few versions of them depending on the background. Also sizes had to be adjusted last time if I remember correctly

**Comment by bhavesh-activatemedia** [comment]
@andreafalzetti smaller versions of the logos, pngs.
![mfa](https://cloud.githubusercontent.com/assets/5073275/17696199/cb587cba-63a4-11e6-963f-cbdd4298446f.png)
![razumkov](https://cloud.githubusercontent.com/assets/5073275/17696200/cb5c05a6-63a4-11e6-8932-2904b043055d.png)
![dcaf](https://cloud.githubusercontent.com/assets/5073275/17696201/cb5c1d98-63a4-11e6-88ac-e13e23d643a1.png)

**Comment by bhavesh-activatemedia** [comment]
@karinapriajina Can you supply the MFA logo in white text? As it is not readable in black: http://dcaf-ua.activatemedia.com

**Comment by karinapriajina** [comment]
![ro_bz_logo_1_rgb_diap_en](https://cloud.githubusercontent.com/assets/15872221/17726582/489eeb28-6454-11e6-8580-8bb2bb21093f.png)

**Comment by bhavesh-activatemedia** [comment]
@andreafalzetti resized logo, same size to replace exiting one
![mfa](https://cloud.githubusercontent.com/assets/5073275/17730066/f43400c2-645e-11e6-909a-029b1e9a8e46.png)

**Comment by andreafalzetti** [comment]
@bhavesh-activatemedia can you replace the image using the widget?

**Comment by bhavesh-activatemedia** [comment]
Thats been updated.

**Comment by bhavesh-activatemedia** [comment]
Bhav to make all images the same size and move the images to the top

**Comment by bhavesh-activatemedia** [comment]
@karinapriajina images have been resized. Thoughts? Remember you can edit the copy in appearance > widgets

**Comment by karinapriajina** [comment]
Hi there! Looks good. 
Only one: the Netherlands section appears to be far away from the rest, can we move it closer so visually the space between all looks similar?
Also I am going to delete an unnecessary word there now.

**Comment by karinapriajina** [comment]
done

**Comment by bhavesh-activatemedia** [comment]
@karinapriajina All three columns are the same width and the logos are all the same height with the same amount of padding. Its an optical illusion that the third column is far away compared to the others as I think because the first columns title is longer and the logo is wider

**Comment by karinapriajina** [comment]
oki. 
Before I forget, y reminder that the photo credit should also appear somewhere on the homepage

**Comment by bhavesh-activatemedia** [comment]
#33 :)
