### ISSUE TITLE
Publications hyperlink

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#36]
Some publications will not be hosted by our website, is there a way to gracefully provide a space for hyperlinking pdfs from their original source? In the abstract?

**Comment by bhavesh-activatemedia** [comment]
Front end: Stays the same
Back end: Currently we have 3 buttons to upload a pdf. Add 3 more fields to add weblinks for each language

**Comment by andreafalzetti** [comment]
@karinapriajina this is ready! As agreed I've added 3 extra fields as you can see from the screenshot below or from the WordPress back-end right now.

If you want to link to an external PDF, just paste the link in the right field (there are 3: english, russian, ukrainian). The PDF upload will have priority in case you have both file and URL for the same language (this case should not happen but in case of any mistake you know how it works).

Please test the funcionality when you have a moment and let me know if there's any problem with it. 

![publications-back-end](https://cloud.githubusercontent.com/assets/2318450/17667094/502ce962-62fb-11e6-93ea-dd66ee5a38ca.jpg)

Thanks

**Comment by karinapriajina** [comment]
Thanks a lot Andrea! I have already tested quite a few ;) they work fine! :) Thanks, well noted!

**Comment by karinapriajina** [comment]
Minor issue: The publication date is stuck on the 8th of August (year is fine).
Is it supposed to let me change days of the month or only months?
