### ISSUE TITLE
About Blanc 

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#37]
In Activities:
- Other Activities
- Opinion Polls

**Comment by bhavesh-activatemedia** [comment]
Investigate why these are not linking

**Comment by andreafalzetti** [comment]
In the current menu they are just placeholders. What are them? Pages? @karinapriajina

**Comment by karinapriajina** [comment]
Hi there! Yes they are supposed to be pages.

**Comment by andreafalzetti** [comment]
If you create the pages, we can then link them from the menu

**Comment by karinapriajina** [comment]
Ok, they should now be available.

**Comment by andreafalzetti** [comment]
I've added the pages to the menu.
