### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#39]
Please change:
Geneva Centre for the Democratic Control of Armed Forces (DCAF)
www.dcaf.ch
**NIS Division** to "NIS Programmes"
Chemin Eugène-Rigot 2E
CH-1202 Geneva
Switzerland
Email: dcaf.ukraine@dcaf.ch

**Comment by bhavesh-activatemedia** [comment]
1. Edit text
2. Remove right hand column
3. Amend copy to make it clearer

**Comment by bhavesh-activatemedia** [comment]
I've updated the copy
