### ISSUE TITLE
Publications - Best Practices Section

### ISSUE THREAD

**Issue by adrian-activate** [ActivateMedia/DCAF-Ukraine#4]
This is a list of publications with links through to individual publication pages.

For an example - https://www.transparency.org/whatwedo/publications/

**Comment by adrian-activate** [comment]
@karinapriajina can we get a list of all of the info you want to add for each publication.

e.g.
- Cover image
- Title
- Description
- Date Published

**Comment by adrian-activate** [comment]
Same as Marsad

**Comment by adrian-activate** [comment]
@karinapriajina Will we have these taxonomies - countries and series as on Marsad?

**Comment by karinapriajina** [comment]
Dear Adrian, 
would you mind re-phrasing your question? I'm not sure I understand.
Many thanks.

**Comment by adrian-activate** [comment]
Sure, on http://marsad-eg.marsad.activatemedia.com/publication/ the tags are organised into 4 categories Themes (this I guess is like your topics), Actors (you have this), countries and series. We were wondering if you will also have countries and series?

**Comment by karinapriajina** [comment]
Ah, oki.  No we won't be needing series nor countries, so just the two (topics, actors) will be enough :) Thanks
