### ISSUE TITLE
Admin access

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#41]
Admin access for our Ukrainian counterparts for uploading translated content
a way to ensure no content is lost or deleted accidentally
security implications

**Comment by bhavesh-activatemedia** [comment]
To investigate various options/plugins to enable monitoring and avoid accidental deletions

**Comment by karinapriajina** [comment]
ogienko@razumkov.org.ua is the e-mail address of our Ukrainian admin person. His name is Viktor. If we could limit their access to only the Ukrainian content as you suggested that would avoid any potential future mis-handling issues.

**Comment by andreafalzetti** [comment]
I have created a Wordpress account for Viktor and I've added him as English to Ukrainian translator. He can login with username: **viktor** and the following password: **I#mUuxjy47mfj5SP7)BJ8M5v** and he will have a view like this:

![screen shot 2016-08-25 at 09 50 53](https://cloud.githubusercontent.com/assets/2318450/17962612/9748a132-6aa9-11e6-93aa-9173338faacf.jpg)

In the screenshot above, I have assigned him the translation of 2 publications. I'm going to remove this assignment so you can decide what to translate first. The translation management happens in the WPML section of the back-end (click on **WPML** in the left-hand side menu) then **Translation Management**. To assign a new job, select the items you want to translate and the language (Russian, Ukrianian or both), select the translator (in this case you only have Viktor but you can have multiple translators) just click confirm (Add translation to basket - the blue button at the bottom).

I have recorded for you how to assign translations of Pages, Posts or Publications to a translator:

## Step 1 - Add translations to the Basket

![page-trans-l](https://cloud.githubusercontent.com/assets/2318450/17963591/2bab321e-6aae-11e6-89a4-e61b323f67c8.gif)

## Step 2 - Assign basket to a translator

![assign-l](https://cloud.githubusercontent.com/assets/2318450/17963555/0482ffe6-6aae-11e6-935c-1d06bf46422f.gif)

In the section explained above you can assign the translation of Pages/Posts/Publications but a translator can also translate the Menus, Widgets, Topics, Tags, etc, etc. You can assign this type of translation in the **String Translation** page (inside WPML in the left-hand menu).

I've recorded a video for this task too:

![string-translation](https://cloud.githubusercontent.com/assets/2318450/17963504/d5fa9896-6aad-11e6-878a-5de4d60553cc.gif)

## Additional Informations about Translation Management

I have collected for you a few links that may help you using this tool.
- [Using WPML’s Translation Management](https://wpml.org/documentation/translating-your-contents/using-the-translation-editor/)
- [Translation Management Features](https://wpml.org/documentation/translating-your-contents/using-the-translation-editor/translation-management-features/)

**Comment by karinapriajina** [comment]
Thank you so much Andrea! I will familiarise myself with this. Thank you so much for making such a thorough and well-illustrated explanation! It's really great.   :)

**Comment by karinapriajina** [comment]
Hello there! I am learning about WPML and the translation and I have come across an important issue. We, as you can see from the English content, have quite a lot of images/graphics, which have to be translated. I notice that for the translators there is no "add media" button while on the job. How do you suggest we override this problem? How can translated graphics be added to the translation?

Many thanks!

**Comment by karinapriajina** [comment]
Dear all, hopefully tomorrow I will be explaining to our translator how to upload the Ukrainian content, I would like to know what to tell him about the graphics. Is it possible for him to handle the process entirely, or should I upload the graphics after the has finished the job?

**Comment by andreafalzetti** [comment]
He should be able to do it

**Comment by karinapriajina** [comment]
Could you kindly explain to me how to? I was trying to understand and couldn't identify the option to upload or edit pictures. This is what I see:
![image](https://cloud.githubusercontent.com/assets/15872221/18706773/9c7ed130-7ff3-11e6-8d30-c9872d2a9b2f.png) No option to upload here.
![image](https://cloud.githubusercontent.com/assets/15872221/18706779/a3738ea4-7ff3-11e6-9085-469e2ab737c0.png) When I go to edit the cloned picture, no option to upload here either.

**Comment by andreafalzetti** [comment]
There is an option in WPML to use the same fields of the original (including tags and featured image). Would that be good for you?

**Comment by karinapriajina** [comment]
Hi Andrea! Sorry I wrote this on slack: The image is also translated so it has to be changed, it's not the same as the original, the text is translated...

**Comment by karinapriajina** [comment]
A question about string translation: I don't really understand all the widgets, how do I know which ones are to translate? I suspect there are some remaining from the building phase... 
For example, I have idea what some of these correspond to or whether they need translating:
![image](https://cloud.githubusercontent.com/assets/15872221/18710745/0fef91aa-8007-11e6-8c4b-e3ed5299c257.png)

Is it safe to say I cannot just select all the widgets and send for translation?

**Comment by karinapriajina** [comment]
Do these all of these items need translation? If not which ones do?
![image](https://cloud.githubusercontent.com/assets/15872221/18710828/7659ed50-8007-11e6-906a-25f1912a25e5.png)

**Comment by andreafalzetti** [comment]
Regarding the widgets: I think that WPML keeps track (and does not delete) all strings contained in Widgets that have been created, even if they have been deleted. If you go to Appearance -> Widgets you will see all the active widgets. There is the possibility to specify the language for each widget, so I would suggest to simply create the same plugin with the same settings and just use the different language, in the front-end it will be only displayed the widgets of the current language. 

Regarding the items of the last message (English form), it's about Mailchimp and we don't need to translate them using WPML, we just need to create a new form when you want to integrate the Ukrainian mailing list.

**Comment by karinapriajina** [comment]
Hi there! Thank you Andrea for your prompt reply. I will look at the active widgets and see if I can identify the ones needed for translation. I don't really understand the part about the plugin though.

RE: ok for Mailchimp

**Comment by andreafalzetti** [comment]
@karinapriajina I meant widget, but I wrote plugin, sorry

**Comment by karinapriajina** [comment]
Hi there! I am probably mentally impaired but I still don't understand which wigets I have to send for translation.... :( 

Also, how do I proceed with the translated images? Do I edit the ukrainian posts myself and add them since the translator apparently can't?

**Comment by andreafalzetti** [comment]
Hi @karinapriajina as I wrote above, regarding the widgets, I would not use WPML to "translate" them but I would suggest to create a version in english (which already exists) and one in Ukrainian.

> If you go to Appearance -> Widgets you will see all the active widgets. There is the possibility to specify the language for each widget, so I would suggest to simply create the same plugin with the same settings and just use the different language, in the front-end it will be only displayed the widgets of the current language.

Example:
![screen shot 2016-09-27 at 10 23 46](https://cloud.githubusercontent.com/assets/2318450/18867526/820f8d50-849c-11e6-998a-1e9e1363cb70.jpg)

Regarding the images, it seems that doesn't allow to upload an image from the translator view so for the moment please change the images from your account.

**Comment by karinapriajina** [comment]
Dear Andrea,

Thank you again for your response. Apologies for the delay, I was home, sick yesterday. Let me see if I understood correctly. Since our translator only has access to WPML, I would have to go into the back end in my account and create a Ukrainian version of the widgets myself is that right? Would you mind guiding me through the steps if that were the case?

Thank you for your help and patience!

Karina

**Comment by andreafalzetti** [comment]
Hi @karinapriajina, I'm sorry to hear that! No worries, creating the widgets is really simple as they are already there in English and you just need to create a duplicate and put the text in Ukrainian. We can go through the process together on Skype. Let me know when you will work on that, and we can schedule a quick call. Take care!

**Comment by karinapriajina** [comment]
Hi Andrea! Would 11 am Geneva time work for you? In 30 min...? :)

**Comment by karinapriajina** [comment]
my skype id is: karina.priajina

**Comment by andreafalzetti** [comment]
Hi @karinapriajina, sorry I didn't see the message! Can we do it around 14 UK time?

**Comment by karinapriajina** [comment]
Hi Andrea, sure, no problem. Talk to you then :)

**Comment by karinapriajina** [comment]
A question to review while we're on translation as well.  In the translation management job assignment list the only items listed are pages and publications. Where do I find the Topics and Actors?

**Comment by karinapriajina** [comment]
Dear @andreafalzetti , 
I was wondering, when translating publications, Viktor does not have to do anything when it comes to uploading PDFs and external links right? What if hypothetically speaking he had a publication in Ukrainian in his possession, could he upload it directly or is it better I upload it from the English side? (notice when translating publications, the PDF and external links are empty).

Thank you!
Kind regards,

Karina

**Comment by andreafalzetti** [comment]
Hi @karinapriajina, I hope you had a nice weekend! Regarding the publications, Viktor now has Admin role so he can see the same interface that you see plus he has the "translator view" but it seems to be limited so I'm not sure if he is able to upload using that view (probably no) but using the "duplicate content from english" in the normal view will copy the PDF links (if it doesn't please let me know as it might need an configuration) so nobody has to re-upload/re-link them. I hope it helps you. Andrea

**Comment by karinapriajina** [comment]
Hi @andreafalzetti! I had a great week end, thank you! How about you? I was asking about the publications because I tried to see how it worked for Viktor and when I copied English content to the translation the pdf's and external links were empty.... so that means it does need some adjustment. (?)

**Comment by karinapriajina** [comment]
[menu-items.xlsx](https://github.com/ActivateMedia/DCAF-Ukraine/files/538322/menu-items.xlsx)
[tags-tabs-and-other-items.xlsx](https://github.com/ActivateMedia/DCAF-Ukraine/files/538323/tags-tabs-and-other-items.xlsx)
[widgets.xlsx](https://github.com/ActivateMedia/DCAF-Ukraine/files/538321/widgets.xlsx)

**Comment by bhavesh-activatemedia** [comment]
@andreafalzetti to update all the plugins. Test Google Analytics
