### ISSUE TITLE
Newsletter subscription on demand 

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#42]
Which is the way of letting people voluntarily subscribe to the newsletter from the website
Could you recommend any cool newsletter templates?
An option to cancel subscription

**Comment by bhavesh-activatemedia** [comment]
Karina to have a look at the way Marsad works for newsletters also to check MailChimp

**Comment by andreafalzetti** [comment]
@karinapriajina have you thought about the newsletter? I can make it as Marsad where you have 3 lists in Mailchimp (one for each language) and we use subscribe form within a modal (popup) that allows users to voluntarily subscribe. The benefit of using a form within a modal is that we can add multiple buttons/links in the site that trigger the modal to open.

**Comment by karinapriajina** [comment]
This sounds interesting! I have to run now, can we talk about this tomorrow and about the acordeon plugin? Are you available in the morning? Let me know and I'll be there

**Comment by karinapriajina** [comment]
Silly question, is the free mailchimp subscription enough for a newsletter campaign?

**Comment by andreafalzetti** [comment]
MailChimp offers a free plan, which DCAF is currently using and is described as following:

**Mailchimp**: If you have fewer than 2,000 subscribers, you can send up to 12,000 emails per month absolutely free. No expiring trial, contract, or credit card required.

I've checked on your (DCAF) account and you currently have 1,753 subscribers (in 13 lists). With this information at hand, I would probably recommend having a specific account for this project so you can start fresh with the 2,000 subscribers.

**Comment by karinapriajina** [comment]
Thank you Andrea for all the useful info! I will open an account as soon as I'm done with the content then :) Will probably need you advice on the newsletter :)

**Comment by karinapriajina** [comment]
Hello there,
Hope all is well!
Could we talk about setting up the monthly automated newsletter please (like the one for Marsad)? Many thanks!

**Comment by karinapriajina** [comment]
[REGULAR newsletter.docx](https://github.com/ActivateMedia/DCAF-Ukraine/files/641759/REGULAR.newsletter.docx)

**Comment by karinapriajina** [comment]
Question: Is the "Democratic Security Sector Governance Website Launch" (243) list actually the list to which people subscribe when hitting the button on the website? If not, how do we make it that list?

**Comment by bhavesh-activatemedia** [comment]
@karinapriajina I just did a test subscription and my name was added to the 'Democratic Security Sector Governance (5)' list and not the 'Democratic Security Sector Governance Website launch (243)' list. @andreafalzetti Can you change it so it adds to the latter.

**Comment by karinapriajina** [comment]
Dear all,

Could we please hide the subscribe button? 
Many thanks.

**Comment by bhavesh-activatemedia** [comment]
@karinapriajina This is the subscribe button on the footer right? So the title should be changed to 'Social' only?

**Comment by bhavesh-activatemedia** [comment]
@karinapriajina I've actioned the above. Let me know if its ok. The translations need to be changed accordingly. You can edit the footer here: Appearance > Widgets > Footer 4

Add the following code in the boxes when you want to reinstate the subscribe button:

english: `<button class="btn btn-default newsletter-english"><i class="fa fa-envelope-o"></i> Subscribe to Newsletter</button>`

ukrainian: `<button class="btn btn-default newsletter-english"><i class="fa fa-envelope-o"></i> Підписатися на Розсилку</button>`

russian: `<button class="btn btn-default newsletter-english"><i class="fa fa-envelope-o"></i> Subscribe to Newsletter</button>`

**Comment by karinapriajina** [comment]
Thank you! I think the simples solution would be to just have no title because I have no idea how to call that in ukrainian, so without a title I think it's still pretty clear.

**Comment by karinapriajina** [comment]
Done! Thanks again :)

**Comment by karinapriajina** [comment]
Question: do you think I could reuse the template we've set up in mailchimp for custom newsletter? Which would be best? The launch template? It would be to announce one thing at a time, like a book being published or similar. 

Thanks!

**Comment by bhavesh-activatemedia** [comment]
@andreafalzetti to double check how subscribers joined if there's no link

**Comment by andreafalzetti** [comment]
I have disabled all plugins related to Mailchimp, there is no way to subscribe to the list from the website.

**Comment by karinapriajina** [comment]
Many thanks Andrea!
