### ISSUE TITLE
Image Optimisation

### ISSUE THREAD

**Issue by bhavesh-activatemedia** [ActivateMedia/DCAF-Ukraine#43]
Install a plugin to resize and optimize any uploaded images

**Comment by andreafalzetti** [comment]
I've installed [EWWW Image Optimizer](https://en-gb.wordpress.org/plugins/ewww-image-optimizer/). It will resize images on upload, for a max-width of 1600 and a max-height of 900 pixels. This can be configured in the [Settings page](http://dcaf-ua.activatemedia.com/wp-admin/options-general.php?page=ewww-image-optimizer%2Fewww-image-optimizer.php) of the plugin.

**Comment by bhavesh-activatemedia** [comment]
@karinapriajina to let us know how the default image should look

**Comment by bhavesh-activatemedia** [comment]
Bhav to create the images and send to @karinapriajina

**Comment by bhavesh-activatemedia** [comment]
![publications_image3](https://cloud.githubusercontent.com/assets/5073275/17696308/6737dc20-63a5-11e6-876b-6b468ab7acb2.jpg)
![publications_image2](https://cloud.githubusercontent.com/assets/5073275/17696307/6737f4a8-63a5-11e6-9a71-904ed32312ec.jpg)
![publications_image1](https://cloud.githubusercontent.com/assets/5073275/17696309/673d2e8c-63a5-11e6-8d04-7aea8109de83.jpg)
