### ISSUE TITLE
Social Sharing Icons

### ISSUE THREAD

**Issue by bhavesh-activatemedia** [ActivateMedia/DCAF-Ukraine#44]
![screen shot 2016-08-05 at 14 14 48](https://cloud.githubusercontent.com/assets/5073275/17437682/0d6a0132-5b17-11e6-948c-3641cdf3c581.png)

Did you want these icons to be in black or in colour?

**Comment by karinapriajina** [comment]
Maybe colour is better? The site is already kind of dark....
What do you think?

**Comment by bhavesh-activatemedia** [comment]
Agreed. @andreafalzetti I'll get you the hex codes for each icon

**Comment by bhavesh-activatemedia** [comment]
@andreafalzetti:

@facebook: #3b5998
@twitter: #00aced
@googleplus: #dd4b39
@pinterest: #cb2027

**Comment by andreafalzetti** [comment]
The colours have been added. Do we want to make the email icon white or light gray or leave it black?

**Comment by bhavesh-activatemedia** [comment]
try this: #5a5463

**Comment by andreafalzetti** [comment]
Thanks
