### ISSUE TITLE
Tools & Other Resources page

### ISSUE THREAD

**Issue by bhavesh-activatemedia** [ActivateMedia/DCAF-Ukraine#45]
Page is too long. @andreafalzetti to install an accordion plugin to allow collapsable sections.

**Comment by andreafalzetti** [comment]
I have implemented the accordion, please have a look 

http://dcaf-ua.activatemedia.com/tools-and-other-resources-2/

If you like it @karinapriajina I can show you how to use this new plugin so you can build it as you want.

**Comment by karinapriajina** [comment]
Yes please! Would you have time this morning? :)

**Comment by karinapriajina** [comment]
The Tools and Resources Section is complete

**Comment by karinapriajina** [comment]
Anything else I need to do here? Is the editing mode be available once it's on the website?

**Comment by andreafalzetti** [comment]
The editing mode can be enabled at any time, even when we go live.

**Comment by karinapriajina** [comment]
Wonderful! Thanks!
