### ISSUE TITLE
codes of conduct

### ISSUE THREAD

**Issue by bhavesh-activatemedia** [ActivateMedia/DCAF-Ukraine#47]
plugin doesnt allow empty paragraphs. @andreafalzetti to investigate

**Comment by andreafalzetti** [comment]
I have installed **Spacer**, a plugin that extends the rich text editor with an additional button. Click on the button shown in the screenshot below to add the space of a default text line.

![screen shot 2016-09-05 at 09 40 11](https://cloud.githubusercontent.com/assets/2318450/18242177/ed729b34-734c-11e6-8392-dbd8b8dddf18.jpg)

**Comment by karinapriajina** [comment]
Thanks a lot!
