### ISSUE TITLE
Publication listing

### ISSUE THREAD

**Issue by bhavesh-activatemedia** [ActivateMedia/DCAF-Ukraine#48]
Move the title and sharing icons to the right of the image as per the marsad site

**Comment by karinapriajina** [comment]
Hi there! This is to say that the 'read more' tag doesn't seem to work...on the sense that is doesn't provide the opportunity to click on it. Also I have tried inserting it manually but it cuts words in half anyway..

**Comment by andreafalzetti** [comment]
Hi @karinapriajina, we might need to adjust some code in the front-end in order to make the read-more tag work. I will run some tests and let you know.

**Comment by karinapriajina** [comment]
Hi Andrea! Many thanks!

**Comment by andreafalzetti** [comment]
I have implemented the read-more tag in the publication listings. Can you double check if it's working properly?

**Comment by karinapriajina** [comment]
Hi there! Unfortunately it does not work...it does seem to cut the text as supposed to in the listing, but then does not offer to read more, and once you click onto a publication it displays read more there for some reason and does not allow to click again (although I don't see why you would have to go somewhere from there to read more...)

**Comment by andreafalzetti** [comment]
I'm still working on the inner page so please ignore that - Talking about the listing, what I wanted to achieve first is cutting the text at the point you decide (not randomly). Now we can add a link that says "Read more" or "Continue" or an icon. I will add the link with "Read More" for the moment, if you want to change the text please let me know what you want to use :)

**Comment by karinapriajina** [comment]
Oh oki, sorry. Yeah so it seems to cut the text all right :) "Read more" is fine as long as it is clearly distinguished from the main text as "...read more" or "...**read more**" or something like that

**Comment by karinapriajina** [comment]
A thought: now that there are a few publications, the "older posts" at the bottom seems obsolete as these are not posts, as well as not too visible/obvious. Also, do you think it would be useful to add "go to top" button maybe to make navigation easier?

**Comment by andreafalzetti** [comment]
The read more functionality should be completed. I made the link readable and tested with few publications. I guess you don't want to cut the comma as per below:

![screen shot 2016-08-15 at 11 39 13](https://cloud.githubusercontent.com/assets/2318450/17662397/10754562-62dd-11e6-890c-87cc1d5e9a3b.jpg)

Besides that, I think it looks good now. What do you think @karinapriajina?
![screen shot 2016-08-15 at 11 38 44](https://cloud.githubusercontent.com/assets/2318450/17662399/16129880-62dd-11e6-8f2e-b927114918ef.jpg)
![screen shot 2016-08-15 at 11 38 54](https://cloud.githubusercontent.com/assets/2318450/17662400/1625e282-62dd-11e6-9d47-3d3458778cdb.jpg)

---

Regarding the "older posts" link I think that comes by default with the current WordPress theme, if you like we can implement a standard pagination as Marsad, [view here](http://www.marsad.eg/en/publication).

**Comment by karinapriajina** [comment]
Thank you Andrea! Yes, that would be great to have a standard pagination as Marsad :)

**Comment by karinapriajina** [comment]
Hello there! Hope all is well! Thanks for all the good work yesterday btw! 
I have que question: I am uploading publications and when I get to the tagging phase I notice a lot of topics are missing from the list. Is this something I can remedy myself? Do they reflect automatically the menu items? I see there are still some "testing" items. I am afraid to delete them and mess something up. Could you maybe scan the posts for me and delete all the test/dummy content that I might have missed or am afraid to touch? Thanks a lot! Let me know about the tags ;)

**Comment by andreafalzetti** [comment]
You can delete any content that is not relevant, no worries. If any Topic is missing, you should add it.
