### ISSUE TITLE
Topics - Fact Sheet pages

### ISSUE THREAD

**Issue by adrian-activate** [ActivateMedia/DCAF-Ukraine#5]
Fact sheets will consist of a description of the topic and a listing module with related (other content on the site that is tagged with the topic title of the page) -
- publications
- institutions
- news
- events

Other topics that are mentioned in the text will be auto linked - need to search for a plugin

**Comment by adrian-activate** [comment]
The pages to begin with will be -

HUMAN RIGHTS:
INTERNATIONAL LEGISLATION
NATIONAL LEGISLATION
FOCUS AREAS
RECOMMENDATIONS

ANTI-CORRUPTION:
BUILDING INTEGRITY
CODES OF CONDUCT
POLICY
PLANNING
BUDGETING
OVERSIGHT
TRANSPARENCY
ACCOUNTABILITY
WHISTLE-BLOWING

PROCUREMENT:
ACQUISITION 
INTEGRITY PACTS
OFFSET ARRANGEMENTS
NEEDS ASSESMENT
MONITORING
EVALUATION
WHISTLEBLOWING
MONITORING

AUDITING
INDEPENDENT MONITORING
REPORTING
WHISTLE-BLOWING
BEST PARCTICES
TOOLS

GENDER:

LEGISLATION:
NATIONAL LEGAL FRAMEWORK
INTERNATIONAL STANDARDS
BEST PRACTICES

**Comment by adrian-activate** [comment]
@karinapriajina does every item listed above have a page?

**Comment by karinapriajina** [comment]
I have updated the menu, and every item in the menu (which is a slightly re-organised version of the above) has a page, yes.

**Comment by karinapriajina** [comment]
But I did not fill in the actual pages, if that's what you mean, these are just "place holders" I guess. Not all of them, some of them are filled.
