### ISSUE TITLE
Publication Series and Countries

### ISSUE THREAD

**Issue by andreafalzetti** [ActivateMedia/DCAF-Ukraine#52]
Hi @karinapriajina,

I can see from the back-end that we have Publications **Series** and **Countries**. I recognise they come from Marsad - I wonder if you use them or not.

If you do, I will implement the display module in the front-end. If you don't I will remove them.

Thanks,
Andrea

**Comment by karinapriajina** [comment]
Hi Andrea! 
Thank you for noticing! Nope, we don't use these features, you can remove them. Thank you. :)

**Comment by andreafalzetti** [comment]
Thanks @karinapriajina. I have removed them. I've left a copy of the code in case you decide to use them in the future.

**Comment by karinapriajina** [comment]
Thank you! That's great :)
