### ISSUE TITLE
Topics: Security Sector Oversight

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#53]
This item does not allow to put content or open. Could you kindly enable it to function as a normal topic?

**Comment by karinapriajina** [comment]
Name issues with other topics (Security Sector Governance, Security Sector) because they have been re-named and re-organised. Front-end is fine now, all items named as should be, but in the back end things have different names and some are missing from "parent lists"....

**Comment by karinapriajina** [comment]
Best Practice 2...refuses to be renamed to Security Sector and put under (non existant parent) Security Sector Governance

**Comment by karinapriajina** [comment]
![menu topics](https://cloud.githubusercontent.com/assets/15872221/17734458/977c825a-647c-11e6-9247-cb3a4378a492.png)

**Comment by karinapriajina** [comment]
To recap: 
I have tried to clean up and straiten the topics so that relevant tags could be added (when uploading publications and other) to the tags lists and have encountered various problems: There seem to be topics in the topic list that refuse to be deleted or recycled under other names, topics are missing from "parent list" as well.  The front end menu now contains all the names of all the topics in the right order, could someone look at the back end with me and ensure it corresponds (see screen shot)?

**Comment by bhavesh-activatemedia** [comment]
@andreafalzetti Install a plugin to merge topics.
@karinapriajina to make menus links clickable using the method described by Andrea.

**Comment by andreafalzetti** [comment]
I've installed the plugin, its features are:
- merge multiple terms (handy if you have duplicated terms or you decide to merge 2 or more terms/tags)
- change taxonomy type (this allows you to convert a Topic into Actor etc)
- set parent (if you want to group terms into a parent item, you can select them all and do a bulk action instead of doing it manually).

If you need any assistance @karinapriajina let me know

**Comment by karinapriajina** [comment]
Dear Andrea,

Thank you. Yes please! When you have a moment, I would love to walk through a practical application of this, a "new plugin for dummies" sort of thing ;)

Thanks again!

:)

**Comment by karinapriajina** [comment]
The legislation globe or sphere or circle is still missing from the Home page as a result of the cleaning up mishap.  
I guess that's issue #54 ...
