### ISSUE TITLE
Menu-Topics-Tags Mess-up issue

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#54]
Hi there! 

So I was cleaning up topics in order to get the tags to correspond to them and this has first created an issue in the menu, where stuff moved around. Which then made the front end look weird...and the text in the circles messed up..... I have now ( or at least I think I have) fixed the menu, the tags and the topics, but while moving things around, the "Legislation Circle Icon" has disappeared from the front end... and other circles don't look too good (this is why I was afraid of deleting stuff)

So please, can someone verify that the menu, the topics, the tags and the front end all correspond to each other? Is it possible to limit the text in the circles and not in the menu? For example in the menu It's security sector legislation, and in the circle it can Security Sector # Legislation

Also: 
- There are still "Best practices" Topics out there and I have no idea what to do with them. Could someone please take care of them? ( I am not deleting any more items)
- Some items in the menu still seem to have some issues and I don't know whether they are important or not such as navigation labels not corresponding to the original labels in: security sector governance, security sector (under SSG).

**Comment by karinapriajina** [comment]
![menu topics](https://cloud.githubusercontent.com/assets/15872221/17811885/063f270c-6625-11e6-90b2-6077bd9e98b1.png)

**Comment by karinapriajina** [comment]
Above the correct disposition of topics. It might be helpful. The menu is supposed to correspond, and tags looked somewhat closer to this last time I looked. I am now moving onto the Tools and Resources content upload task... 

I am really sorry for this mess. But it's better I don't do any more cleaning up....

**Comment by karinapriajina** [comment]
PS: The issue with the names is that if Security Sector Oversight is shortened to Oversight, it becomes exactly the same a  subtopic of Anti-Corruption --> Oversight....which makes thing difficult to discern when tagging

**Comment by bhavesh-activatemedia** [comment]
@karinapriajina these things happen, dont worry. i'm sure its all there.

**Comment by karinapriajina** [comment]
PS2: I need the Main Topics in the menu to remain the same, front end circles leading to them can be shortened to (right to left and top to bottom)
1) Anti-Corruption          2)Human Rights      3)Oversight
4)Governance                  5)Procurement         6)Legislation

**Comment by karinapriajina** [comment]
Thank you again Bhavesh! 
It's always frustrating when they do.... for all of us!

**Comment by karinapriajina** [comment]
The search bar does not work, I suspect that it's the same issue

**Comment by andreafalzetti** [comment]
@karinapriajina I've fixed the search box, somehow it disappeared from the menu :)

**Comment by bhavesh-activatemedia** [comment]
@karinapriajina we are currently fixing the homepage issue with the circles. Could you clarify:
1. What should the titles of the circles be?
2. That they are all linking to the correct sections
3. They are in the right order

**Comment by karinapriajina** [comment]
Hi there! Wonderful! Sure :) 

The first line of circles from left to right:
1) Should be called (a shortened)"Anti-Corruption" and should link to "Anti-Corruption and Security Sector" section/topic and subtopics (currently not displayed in any way). Topic names in the menu should remain the same if possible (a more complete version).
2)Should be called "Human Rights" and should link to "Human Rights and Security Sector" section/topic and subtopics.
3) Should be called "Oversight" and should link to "Security Sector Oversight" section/topic and subtopics.

The second line of circles from left to right:
4) Should be called "Security Sector" and should link to "Security Sector Governance" section/topic and subtopics.
5) Should be called "Procurement" and should link to "Procurement" section/topic and subtopics.
6) Should be called "Legislation" and should link to " Security Sector Legislation" section/topic and subtopics.

Unless there is a way to squeeze the full names into the circles....

**Comment by bhavesh-activatemedia** [comment]
@karinapriajina For consistency we believe the titles in the circles should be the same throughout the site. The font size has been reduced, line removed to make more space and 'read more' moved as far as possible to the bottom of the circle.

Is this correct?

Circle 1:
Anti-Corruption and Security Sector
http://dcaf-ua.activatemedia.com/topic/anti-corruption/ 

Circle 2:
Human Rights and Security Sector
http://dcaf-ua.activatemedia.com/topic/human-rights/

Circle 3:
Security Sector Oversight
http://dcaf-ua.activatemedia.com/topic/anti-corruption/oversight/
change to
http://dcaf-ua.activatemedia.com/topic/security-sector-oversight/

Circle 4:
Security Sector Governance 
http://dcaf-ua.activatemedia.com/topic/security-sector-governance/security-sector/
change to
http://dcaf-ua.activatemedia.com/topic/security-sector-governance-2/

Circle 5: 
Procurement
http://dcaf-ua.activatemedia.com/topic/procurement/

Circle 6: 
Security Sector Legislation
http://dcaf-ua.activatemedia.com/topic/security-sector-legislation/

**Comment by karinapriajina** [comment]
Good morning Bhavesh! 

The names of the circles are correct. I don't understand what the links are for though (?)
Additionally, how can we make the subtopics appear on the page of the main topic?
Within this space, is the appearance of the publications going to be adjusted (currently they are very big and stretched) ?

Many thanks!

**Comment by karinapriajina** [comment]
BTW: I finally managed to put Security Sector Governance and Security Sector in the right order. haha

**Comment by karinapriajina** [comment]
Weird occurrence in Actors: 
Democratic institutions has no parent. However, when opened, the route on top for some reason says: " Publications>Democratic institutions "

**Comment by bhavesh-activatemedia** [comment]
@karinapriajina The icons and titles have been updated. They now point to the correct pages.

The issue to resolve now is the order that they appear. We can order them easily by the following parameters:
- Term ID
- Term Name
- Term Slug
- Term Group

If you want them in another order we will have to spend some time looking into hacking this. What would you like to do? Is the specific order important?

**Comment by karinapriajina** [comment]
Hi there! They have moved around. If you don't want to spend too much time re-arranging them into the order specified above, I will be happy if you just move procurement down to the second row and put either oversight or legislation in its place.

**Comment by bhavesh-activatemedia** [comment]
@karinapriajina For showing subtopics on the main topic pages, 2 options:
1. We have a column on the right which lists the links. This will be relatively easy to add but will obviously reduce the content area making the page even longer. 
2. We can do some research and look into adding a horizontal widget. Will take some time and Im thinking we should get all the other things done to bring the site up to spec and then worry items like this later. Unless this has been identified as an important issue?

**Comment by bhavesh-activatemedia** [comment]
@karinapriajina Looks like ordering the circles via ID is best as it places Procurement on the second row. What do you think?

**Comment by karinapriajina** [comment]
That looks fine, thank you!

**Comment by karinapriajina** [comment]
A column on the right as in here you mean? --> http://dcaf-ua.activatemedia.com/about-this-website/

**Comment by bhavesh-activatemedia** [comment]
@karinapriajina yep

**Comment by karinapriajina** [comment]
That would not do...
I cannot subjectively judge on the importance of this since I only see the appearance-side of all the work, so I don't really grasp the technical implications. However, it is an important part of the website layout, and the point of the circles was to make the same info from the menu even more available to the public, but aesthetically different and therefore more attractive/captivating... the side menu is not cutting it in terms of appeal..

**Comment by karinapriajina** [comment]
speaking of, the publications tiles in the topics also seem to be messy in terms of alignment, that is, sometimes there would be a space, others they are closely together, other times an entire tile is missing....

**Comment by bhavesh-activatemedia** [comment]
Ok I'll open up two new issues for the above points.

**Comment by karinapriajina** [comment]
Thank you very much Bhavesh! :)
