### ISSUE TITLE
Photo credit disappeared again from the welcome page  

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#55]
Not very important at this stage, but just to note that the welcome page has gone back to its format without the credit and will not scroll down. This is just fyi, at this stage we have more pressing issues, like the menu-mess-up.

**Comment by andreafalzetti** [comment]
@karinapriajina Are you sure you are looking at ukrainesecuritysector.com and not to dcaf-ua.activatemedia.com?

**Comment by karinapriajina** [comment]
Hi Andrea! Yep, you're right, I didn't realise those were different. Never mind this then! Sorry :)
