### ISSUE TITLE
Key Actors slug issue

### ISSUE THREAD

**Issue by bhavesh-activatemedia** [ActivateMedia/DCAF-Ukraine#56]
Weird occurrence in Key Actors: 
Democratic institutions has no parent. However, when opened, the route on top for some reason says: " Publications>Democratic institutions " 
Actually, all actors seem to pass through Publications...

http://dcaf-ua.activatemedia.com/marsad_actors/democratic-institutions/

**Comment by bhavesh-activatemedia** [comment]
It must have always been like this. Its been changed.

**Comment by karinapriajina** [comment]
Many thanks Bhavesh!
