### ISSUE TITLE
Publication tile alignment

### ISSUE THREAD

**Issue by bhavesh-activatemedia** [ActivateMedia/DCAF-Ukraine#57]
the publications tiles in the topics also seem to be messy in terms of alignment, that is, sometimes there would be a space, others they are closely together, other times an entire tile is missing....

ie: http://dcaf-ua.activatemedia.com/marsad_actors/parliament/

**Comment by bhavesh-activatemedia** [comment]
@karinapriajina This has been worked on, please review.

We had two options here:
1. Have a fixed size box or
2. Have a fluid box which varies in height dependant on the content

Looking at the pros and cons we felt option 1 would place too many limitations on the content. You will be limited in the number of characters for titles & copy, size of image, number of tags etc. Therefore we have gone with option 2.

You can still add as much content as you wish but now the boxes do not leave an entire empty space but leave smaller gaps as the next row starts at the end of the longest box. Its difficult to explain but if you take a look at the site you can see how it now works. http://ukrainesecuritysector.com/topic/anti-corruption/

**Comment by karinapriajina** [comment]
Dear Bhavesh,
Thank you for this. I will have to see if the rest of team is ok with this arrangement. It should be fine. 

Thanks again!

**Comment by karinapriajina** [comment]
Just checked with the team. We're good to go with this option. Thank you again!
