### ISSUE TITLE
Back to top

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#59]
Dear all,
Would it be possible to include a "Back to top" feature on the web? For user-friendliness purposes?

**Comment by bhavesh-activatemedia** [comment]
@karinapriajina I'm sure there are some widgets that can be added to do this but I would suggest leaving this for the moment. Lets get all the important and necessary issues addressed and closed and then look at feature enhancement.

**Comment by karinapriajina** [comment]
Absolutely! Thanks Bhavesh!

**Comment by karinapriajina** [comment]
I forgot to mention here that "older Posts" at the bottom of the pages are not very user friendly either. First of all, you can barely see the words and second, when you do click on older posts you have to scroll down through the text again, which to an outsider is confusing. Can we please do something there to enhance the navigation user-friendliness? Thank you!

**Comment by andreafalzetti** [comment]
@karinapriajina, I have added the "back to top" button at the bottom-right of the website.

Regarding your last message in this thread, is this still an issue we need to look into?

**Comment by karinapriajina** [comment]
Thank you Andrea!!! Hummm. It's still kind of an issue although I don't really see how we could fix it...

**Comment by karinapriajina** [comment]
Hi there! I was thinking, is there a way to ancor the page-number links to where the posts start rather than letting the page reload from top ? How much of a fuss is this?
