### ISSUE TITLE
Who is involved

### ISSUE THREAD

**Issue by adrian-activate** [ActivateMedia/DCAF-Ukraine#6]
Who is involved
- List of institutions
- Each institution has a page describing its activity
- Each institution has a list of related publications

**Comment by adrian-activate** [comment]
DEMOCRATIC INSTITUTIONS:
PARLIAMENT
MP’S
COMMITTEES
LEGISLATION
JUDICIARY
INDEPENDENT OVERSIGHT INSTITUTIONS
OMBUDS INSTITUTIONS
HUMAN RIGHTS DEFENDERS

EXECUTIVE INSTITUTIONS:
NATIONAL SECURITY COUNCIL
GOVERNMENT
MINISTRY OF DEFENCE
MINISTRY OF FINANCE
MINISTRY OF INTERIOR
MINISTRY OF FOREIGN AFFAIRS

SECURITY SECTOR:
DEFENCE 
LAW ENFORCEMENT
COMMUNITY POLICE
INVESTIGATIONS
PENITENTIARIES
BORDER SERVICE
INTELLIGENCE
FOREIGN 
DOMESTIC

CIVIL SOCIETY AND INTERNATIONAL ORGANISATIONS:
UNITED NATIONS
EUROPEAN UNION
COUNCIL OF EUROPE
ECHR
OSCE
WORLD BANK
TRANSPARENTY INTERNATIONAL 
NATO
DCAF
RATUMKOV CENTRE
CIVIL SOCIETY
MEDIA

**Comment by activate-siva** [comment]
institutions has been changed to actors.
