### ISSUE TITLE
Similar Issue with "Civil Society and Media" 

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#61]
http://dcaf-ua.activatemedia.com/topic/civil-society-and-media/

Civil Society and Media is supposed to be an actor whereas it is currently a topic. There was a new plugin that allowed to merge the two right? How can I convert the topic into the actor?

**Comment by andreafalzetti** [comment]
This plugin makes this operation very easy! See the image below:
1. Select a topic
2. From the dropdown select "Change taxonomy"
3. Select Actors
4. Apply

![screen shot 2016-09-06 at 10 31 16](https://cloud.githubusercontent.com/assets/2318450/18268769/22952fea-741d-11e6-9cc2-2081feb3bc58.jpg)

**Comment by karinapriajina** [comment]
Oki. Thanks! :)

**Comment by karinapriajina** [comment]
Hummm...now it's not allowing to click on it from the menu (front end)

**Comment by karinapriajina** [comment]
and the content has been erased :(

it's still a topic in the menu (back end)

**Comment by andreafalzetti** [comment]
What content has been erased @karinapriajina?

From the menu you probably need to add it again as the type as changed, it's not a topic anymore, the path will be different. 

From the back-end (Topic) I cannot find "Civil Society and Media" but I see it as Actor. Did you manage to fix this?

**Comment by karinapriajina** [comment]
Nope.
I see it as actor too, but I don't know what to do to link it on the front end. I'll try the menu... (fingers crossed). The content that has been put into "Civil Society and Media" as a topic, disappeared when it was converted into an actor... It's not much, so I can add it again, but its could be a problem in the future.... (although I will avoid using it)

**Comment by karinapriajina** [comment]
Ok, it appears as should now :)
Problem solved. The mysterious disappearance remains a mystery though
