### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#63]
Hello everyone! It has been brought to our attention, although, we've known it before, that the addresses in "Contact" are messy. Especially Netherlands MFA...I have tried to solve the problem but I'm afraid my limited knowledge of IT does not allow me to correct the issue as should be since adding spaces and paragraphs in the back end messes up the entire 3-column structure. Could someone please ensure the addresses make sense? Some words can be deleted if necessary (such as "postal address" and similar). Thank you so much!

**Comment by bhavesh-activatemedia** [comment]
@karinapriajina Ive made some changes. What do you think?

**Comment by karinapriajina** [comment]
Perfect! Thank you!
