### ISSUE TITLE
Houston we have a spacer problem again...

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#64]
Dear all, 
As discussed yesterday, I have tried to copy and paste text from descriptions to intros in Topics and.... spacing does don work again. Not the normal paragraph spacing nor the spacer plugin....which I may add just appears with all its letters on the front end. 
Could someone please take a look, because I have no idea what to do? Thank you very much.

**Comment by andreafalzetti** [comment]
Hi @karinapriajina, all [spacer] need to be replaced with an actual empty line. If you give me an example I can show you how to fix it.

**Comment by karinapriajina** [comment]
Hi Andrea! Yes, I have tried to edit the anti-corruption topic we moved yesterday, ans spacing does not obey... :(
http://ukrainesecuritysector.com/topic/anti-corruption/

**Comment by karinapriajina** [comment]
What should I do about this @andreafalzetti ? Standby?

**Comment by andreafalzetti** [comment]
I had a quick look and I would say, the proper way of doing the spacing would be using heading instead of paragraph elements for the title. We could style with CSS the h4 or h5 so that they have some top margin, the only thing you would need to do is change the titles from paragraph to heading 4.

**Comment by karinapriajina** [comment]
Hi @andreafalzetti I have tried it (http://ukrainesecuritysector.com/topic/anti-corruption/) does not really look good.....
:(((

**Comment by karinapriajina** [comment]
Whatever happened to the Google Analytics Preview on WordPress?

**Comment by andreafalzetti** [comment]
@karinapriajina do you remember the Widgets view in the back-end was broken? The Google analytics plugin contains an error that breaks the page, so I currently disabled the widget (there is an option that allows disabling the widgets only) until the next update. Hopefully they will fix this soon. To access the data, simply use the official google analytics website for the moment =)

**Comment by andreafalzetti** [comment]
@karinapriajina I know, now it would not look good. Before we convert paragraph title to actual headings we would need to style them with CSS so they have enough top margin and the correct font size and family.

**Comment by karinapriajina** [comment]
Thank you @andreafalzetti ! So do I still cut and paste them as we said? and we handle styling later? Which is the plan?
:)

**Comment by karinapriajina** [comment]
Dear @andreafalzetti , I have to assign jobs to our translator and I don't know what to assign him since Publications and Posts have not been translated yet and he has no access to topics or actors....

**Comment by andreafalzetti** [comment]
@karinapriajina I would say keep moving the intro text to the description field and we take care of the styling later as you suggested. 

Have the translator translated anything so far?

**Comment by karinapriajina** [comment]
Re text: Oki will do , thanks a lot!

Re translation: Yes, he has completed the upload of the assigned posts today. This means that I have nothing else I can assign to him from WPML (publications and news/events not yet translated by the interpreters). And he has no access to actors...does he?

**Comment by karinapriajina** [comment]
OH! I can assign Tools and other Resources, how would that work for him? Visual Composer?

**Comment by andreafalzetti** [comment]
That's a good idea but I'm not sure WPML supports Visual Composer. I guess the best would be upgrade his account to Editor so he has the same view as you and me and we are sure he has access to everything. I will do this, check from his account what he can see and get back to you. Give me 15 minutes.

**Comment by karinapriajina** [comment]
Oki, thank you so much!

**Comment by karinapriajina** [comment]
It has been assigned, so you can see how it looks for him if you're in his account :)

**Comment by andreafalzetti** [comment]
I have upgraded his role to Administrator as it's the only wat to allow him to access the taxonomy translations in WPML, I don't see this as a problem. 

He has access to visual composer but the 2 plugins are not integrated so from the WPML view he would see some visual-composer code in the wpml editor. The easiest way to translate that page is using visual composer itself.

**Comment by andreafalzetti** [comment]
He has now a lot more menu options in the left hand menu so please tell him that this is normal and he can find the translation view under the WPML menu item.

**Comment by karinapriajina** [comment]
@andreafalzetti I am trying to understand how he can translate with the new configuration, but I don't... I am in his account. Have no idea what to do here to translate. In pages, topics or actors. Could you maybe walk me through the process so I can explain it to Viktor?
Especially when it comes to visual composer

**Comment by andreafalzetti** [comment]
@karinapriajina he can translate pages, posts, taxonomy terms - WPML is fully integrated with the WP views so depending on what you need to translate, he can do it. If you need specific help, ring me on Skype please =)
