### ISSUE TITLE
Quick Check Request

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#65]
Dear Andrea,
Before I send these of to translation, could you kindly have a quick look and tell me if I understood the excel sheets purpose correctly? Thank you so much! 
[menu items.xlsx](https://github.com/ActivateMedia/DCAF-Ukraine/files/500363/menu.items.xlsx)
[tags tabs and other items.xlsx](https://github.com/ActivateMedia/DCAF-Ukraine/files/500364/tags.tabs.and.other.items.xlsx)
[widgets.xlsx](https://github.com/ActivateMedia/DCAF-Ukraine/files/500366/widgets.xlsx)

**Comment by andreafalzetti** [comment]
Hi @karinapriajina, this looks good!

**Comment by karinapriajina** [comment]
Great! Thank you so much Andrea!
