### ISSUE TITLE
Facebook share button  does not work

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#67]
It says Wrong IP.

**Comment by andreafalzetti** [comment]
Hi @karinapriajina, I've solved this issue, apology for the long wait. I tested with my account and it worked, could you please confirm at your end? Thanks!

**Comment by karinapriajina** [comment]
Hi Andrea!!! No worries. I've checked and it says 
![image](https://cloud.githubusercontent.com/assets/15872221/20006248/0d7332da-a297-11e6-90f7-9fbd92e80151.png)

**Comment by andreafalzetti** [comment]
Thanks for checking @karinapriajina - I should have fixed this issue now, can you please try again? 😄

**Comment by karinapriajina** [comment]
Success!!!! Thank you!
![image](https://cloud.githubusercontent.com/assets/15872221/20006365/7d7379dc-a297-11e6-9d74-a10e3277273c.png)

**Comment by andreafalzetti** [comment]
Great! Thanks @karinapriajina 👍  I'll close the issue.
