### ISSUE TITLE
Review hot links plugin

### ISSUE THREAD

**Issue by andreafalzetti** [ActivateMedia/DCAF-Ukraine#69]
Check why it's not linking `OSCE` in http://ukrainesecuritysector.com/osce-pcu-verkhovna-rada-ministry-defence-visit-dcaf-gichd-10-12-october-2016/

and general check up

**Comment by andreafalzetti** [comment]
@karinapriajina I have looked at the source code of the hotlinks plugin, and noticed that only topics were set up to be hotlinked so I've added actors. 

Overall the plugin seems working fine in most cases and it now links the "OSCE" actor above, so please write here any new issue you experience with the plugin so we can improve it.

**Comment by karinapriajina** [comment]
Dear Andrea,
Thank you very much. 
The biggest problem with this plugin is that it randomly dissects manually installed links if there is a word in there which refers to one of the topics or actors. There are always going to be the same words used, so it is always going to be a problem. Also, it is not linking words in actors or in topics.... Frankly I do not think this plugin is working well or makes sense on this website in the first place, could you please disable it? Unless this is going to trigger other complications.... 

I would prefer to take the time to link the relavant pages manually.....
