### ISSUE TITLE
Publication translated and duplication of PDF links / custom fields

### ISSUE THREAD

**Issue by andreafalzetti** [ActivateMedia/DCAF-Ukraine#70]

**Comment by andreafalzetti** [comment]
Hi @karinapriajina, I have worked on WPML options and it seems to work as expected now. When you save a publication now it will duplicate correctly the following attributes:
- author
- english_pdf
- external_english_pdf
- external_russian_pdf
- external_ukrainian_pdf
- publication_isbn
- publication_rating
- russian_pdf
- ukrainian_pdf
- _views_template
- _wpml_media_duplicate
- _wpml_media_featured 

From the list above, `_views_template` is not really relevant for this so please ignore it.
Regarding the two "media" attributes, I have installed an extension of WPML called WPML Media that allows the duplication of attachments and featured images.

I have enabled that for future translations, the image will be automatically duplicated. Of course you have control over this via the WPML sidebar widget that you will find on the right hand side of the editing page, as shown below.

![screen shot 2016-11-04 at 13 24 04](https://cloud.githubusercontent.com/assets/2318450/20007128/cb2b7288-a292-11e6-8203-3aafdb3d5557.jpg)

I have tested all of this with a draft publication, I'll delete it now. If you would like to test this, it would be great! Let me know your feedback so we can close this issue. Thanks 😃

**Comment by karinapriajina** [comment]
Hi Andrea! That looks great. I have tried from Viktor's account and although there is a message that says that content will be copied, when I hit "copy content from English" button ( and although the media attachment boxes are checked) the links and pdfs appear empty

**Comment by karinapriajina** [comment]
Just checked from my own account. Same here

**Comment by andreafalzetti** [comment]
As the message on top says, the content will be copied automatically when you save the translation, have you tried that? I don't think you need to manually copy the content from english :) Let me know if it works!

**Comment by karinapriajina** [comment]
Ah you're right! :) Works from my profile! Let me try from Viktor's

**Comment by karinapriajina** [comment]
Works here too! Thank you !!! :)
