### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#71]
Dear all, 

Viktor has detected a few tiny issues while uploading the translation. The title of this topic (below) does not display in ukrainian in the fron end, although in the back end it has been adapted. 

http://ukrainesecuritysector.com/wp-admin/term.php?taxonomy=topic&tag_ID=119&post_type=post&lang=uk&wp_http_referer=%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dtopic%26lang%3Duk The title does not appear in Ukrainian on the front end

Also, translation of Procurement appears to be missing from "Parent" items. ( I have to check though if this is not merely a matter of procurement as topic not having been translated yet.

**Comment by andreafalzetti** [comment]
@karinapriajina how are you looking at the Ukrainian front-end?

**Comment by karinapriajina** [comment]
Hi @andreafalzetti! That is a fair question. It's not me looking, it's Viktor, and you are right...he should not be seeing the Ukrainian front end, should he? In any case, I checked and all of the above is fine, so never mind. (unless you have solved the issue in which case, thank you very much!)
