### ISSUE TITLE
Widgets in Ukrainian

### ISSUE THREAD

**Issue by andreafalzetti** [ActivateMedia/DCAF-Ukraine#72]

**Comment by karinapriajina** [comment]
[menu-items.xlsx](https://github.com/ActivateMedia/DCAF-Ukraine/files/580960/menu-items.xlsx)
[tags-tabs-and-other-items.xlsx](https://github.com/ActivateMedia/DCAF-Ukraine/files/580962/tags-tabs-and-other-items.xlsx)
[widgets.xlsx](https://github.com/ActivateMedia/DCAF-Ukraine/files/580961/widgets.xlsx)

**Comment by andreafalzetti** [comment]
@karinapriajina I will copy the links of these documents into a Wiki page, so we don't lose them.

Also, this morning I reviewed the footer widgets and adjusted a few things. The footer in Ukrainian looks good to me now. Can you confirm you are happy with it, so I can close this issue please?

**Comment by karinapriajina** [comment]
yep, looks ok to me!
