### ISSUE TITLE
Send announcement newsletter 

### ISSUE THREAD

**Issue by andreafalzetti** [ActivateMedia/DCAF-Ukraine#74]
- [ ]  @karinapriajina to provide @bhavesh-activatemedia the copy for both English and Ukrainian
- [ ] @bhavesh-activatemedia create the newsletter
- [ ] @bhavesh-activatemedia to send the newsletter as soon as we go live on Thursday the 15th of Dec

**Comment by karinapriajina** [comment]
[UKR Launch Announcement.docx](https://github.com/ActivateMedia/DCAF-Ukraine/files/641749/UKR.Launch.Announcement.docx)

**Comment by karinapriajina** [comment]
![image](https://cloud.githubusercontent.com/assets/15872221/21045361/4d91fc64-be00-11e6-98ff-b730cc524f56.png)

**Comment by karinapriajina** [comment]
www.ukrainesecuritysector.com

View this email in your browser / Використовуйте ваш браузер, щоб переглянути це повідомлення  




UKRAINE/ УКРАЇНА
DEMOCRATIC SECURITY SECTOR GOVERNANCE/ ДЕМОКРАТИЧНЕ УРЯДУВАННЯ У СЕКТОРІ БЕЗПЕКИ 



 

We are pleased to announce that Ukraine Democratic Security Sector Governance website is now available in Ukrainian language / З великим задоволенням повідомляємо, що веб-сайт «Демократичне урядування у секторі безпеки» вже доступний українською мовою

Click Here to View the Website / Щоб переглянути веб-сайт, натисніть тут 


 
	 



If you want to hear more about our work, make sure to subscribe to our newsletter. If you have any comments and suggestions, don’t hesitate to contact us at dcaf.ukraine@dcaf.ch Thank You! / Якщо ви бажаєте знати більше про нашу діяльність, підписуйтеся на нашу розсилку. Ваші коментарі та поради надсилайте, будь-ласка, на адресу dcaf.ukraine@dcaf.ch Щиро дякуємо!
 

Click Here to View the Website / Щоб переглянути веб-сайт, натисніть тут

**Comment by bhavesh-activatemedia** [comment]
This has been created. Ready to send out as a test and then a real send
