### ISSUE TITLE
Check publications in ukrianian

### ISSUE THREAD

**Issue by andreafalzetti** [ActivateMedia/DCAF-Ukraine#76]
- [x] Make sure listing page is working
- [x] Make sure menu is linking correctly to the listing page
- [x] check why 2 publications don't appear in the ukrainian version

**Comment by karinapriajina** [comment]
http://ukrainesecuritysector.com/publication/legislating-security-sector-toolkit-argentinian-national-intelligence-law/

http://ukrainesecuritysector.com/publication/legislating-security-sector-toolkit-south-african-military-discipline-supplementary-measures-act/

**Comment by andreafalzetti** [comment]
@karinapriajina the publication listing seem working correctly to me. Also, the are both linked from the menu. In conclusion, the 2 publications that don't appear in the Ukrainian version:

1. http://ukrainesecuritysector.com/publication/legislating-security-sector-toolkit-argentinian-national-intelligence-law/ doesn't have a translation as you can see from the image below:
![screen shot 2016-12-14 at 11 56 54](https://cloud.githubusercontent.com/assets/2318450/21182066/019614b0-c1f9-11e6-9947-1b05970f7b6f.jpg)
2. http://ukrainesecuritysector.com/publication/legislating-security-sector-toolkit-south-african-military-discipline-supplementary-measures-act/ - it seems the problem is the slug. Given the long title, I had to cut off one word from the URL (generated from the slug) and now it's working. It's weird and it's probably because of the Ukrainian letters.

**Comment by karinapriajina** [comment]
aha....Thanks a lot! 
I'll tell Viktor about the first publication
