### ISSUE TITLE
Ukrainian menu

### ISSUE THREAD

**Issue by andreafalzetti** [ActivateMedia/DCAF-Ukraine#77]
- [x] Make sure the uber menu is set up correctly for Ukrainian
- [x] Double check menu items are synchronised correctly
- [x] Add contact

**Comment by andreafalzetti** [comment]
@karinapriajina the menu looks much better now in Ukrainian. The Contact page was now translated yet so what I did was duplicating the english one for the moment, and only translated the title. Please finish the translation of the content if any.

**Comment by andreafalzetti** [comment]
For the following string:
* Name
* Organization
* Email
* Subject
* Message

They are part of the form so if you provide the translations, I will add them.

**Comment by karinapriajina** [comment]
Dear @andreafalzetti thank you very much!
The words are: 
![image](https://cloud.githubusercontent.com/assets/15872221/21173210/ef5434e8-c1d6-11e6-997f-801d28024d8c.png)

 Ім'я
Організація
Email
Суб'єкт
Повідомлення

**Comment by andreafalzetti** [comment]
I have loaded the translations. Sorry, I just noticed they were in the Excell file. Thank you @karinapriajina!

**Comment by karinapriajina** [comment]
Thank you Andrea! No worries, thank you so much for loading them!!!

**Comment by andreafalzetti** [comment]
I was testing the form and I noticed that there are some more messages that need translation:

* Please fill in the required field.
* Your message was sent successfully. Thanks.
* Failed to send your message. Please try later or contact the administrator by another method.

@karinapriajina can you please supply?

**Comment by karinapriajina** [comment]
Thank you for noticing! Yes, I will send these to Viktor for translation and get back to you as soon they're ready

**Comment by andreafalzetti** [comment]
@karinapriajina I fixed the Search menu item. I also translated all search related strings. Please review

**Comment by karinapriajina** [comment]
- Будь ласка, заповніть обов'язкові поля.                                                       
- Ваше повідомлення було успішно надіслано. Дякуємо.                                                    
- Не вдалося відправити повідомлення. Будь ласка, спробуйте пізніше або зверніться до адміністратора в інший спосіб.

**Comment by karinapriajina** [comment]
Are these the translations you used?

**Comment by andreafalzetti** [comment]
Yes, thanks @karinapriajina
