### ISSUE TITLE
Ukrainian text in the English version

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#80]
http://ukrainesecuritysector.com/about-this-website/

The resent posts section on the right hand, is in Ukrainian. Honestly, I don't think this section (resent posts) is useful at all, we can eliminate it all together.

**Comment by bhavesh-activatemedia** [comment]
remove from everywhere besides single news page

**Comment by andreafalzetti** [comment]
I made the "About this website" page full-width and I have excluded the related content / recent news widgets from any page except for the single page news.
