### ISSUE TITLE
Ukraine Site costs

### ISSUE THREAD

**Issue by bhavesh-activatemedia** [ActivateMedia/DCAF-Ukraine#81]
how many working hours it took on your side for us to translate the site into ukr more or less.
I have to work out a budget for the russian translation.

**Comment by bhavesh-activatemedia** [comment]
send Karina breakdown of first quarter times

**Comment by andreafalzetti** [comment]
@karinapriajina looking at the timesheets it seems that we spent 2 days on translating the site. This might not include minor work done across multiple days on which we were working on other tasks so probably if I have to give you a number, I would say 3/4 days.

**Comment by karinapriajina** [comment]
Thank you Andrea!
