### ISSUE TITLE
Listing layout issue in "Events"

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#82]
Dear all, 

There appears to be a layout issue in the listing page of the "events", here: http://ukrainesecuritysector.com/category/events/

It is the same issue we had at the beginning elsewhere on the site too.

Could someone use the same method to reduce the gaps between the tiles please?

Many thanks!

Kind regards,

K

**Comment by karinapriajina** [comment]
Hi there!

Could I ask you to please look into fixing this soon? We have a Conference soon, and since that's when we have most visits I would like for the web to look nice.
Many thanks.

K

**Comment by bhavesh-activatemedia** [comment]
@karinapriajina What date does this have to be done by?

**Comment by bhavesh-activatemedia** [comment]
@andreafalzetti to look into this, see homepage

**Comment by andreafalzetti** [comment]
This should be fixed now. Sorry for the delay @karinapriajina.
