### ISSUE TITLE
Russian Translation

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#83]
Hello everyone!
I hope you are all doing great! This is to let you know that soon we will be uploading the russian translation online. I believe everything is already set up and ready. If someone could do a quick check and see if that is the case and if Viktor still has access to all the necessary features in order to upload the russian text, that would be wonderful.  Many thanks!

Kind regards,

Karina

**Comment by karinapriajina** [comment]
Hi guys! Hope you're doing great! Is there anything that needs to be done before the upload of the russian version begins?

**Comment by bhavesh-activatemedia** [comment]
Hi @karinapriajina, Viktor can be begin the Russian translation work whenever he is ready, there is nothing preventing/stopping him from doing this from a technical point of view. He can start on the taxonomies and pages.

**Comment by karinapriajina** [comment]
Hi @bhavesh-activatemedia ! That's great! Thank you! Could we start thinking about setting a time in your working schedule for working on the translation of words that only you can access? As we did for the ukrainina version? I have the excell documents with the relevant words ready for you. If you think that the necessary time overruns maintenance allowance, let me know . The goal is that we launch the russian version by mid September so we have almost 2 months to import the words.

**Comment by bhavesh-activatemedia** [comment]
@andreafalzetti 
[menu-items ruru.xlsx](https://github.com/ActivateMedia/DCAF-Ukraine/files/1156365/menu-items.ruru.xlsx)
[tags-tabs-and-other-items(ru).xlsx](https://github.com/ActivateMedia/DCAF-Ukraine/files/1156367/tags-tabs-and-other-items.ru.xlsx)
[widgets(ru).xlsx](https://github.com/ActivateMedia/DCAF-Ukraine/files/1156366/widgets.ru.xlsx)

**Comment by andreafalzetti** [comment]
@karinapriajina the Russian language is enabled to administrators and hidden to visitors. I have created the translation for the Homepage so you can see it if you visit:

http://ukrainesecuritysector.com/ru/

(you need to be logged in as Admin with your account, as usual)

Your translator can start populating the content, I did some samples but you will have to carry on.

Let me know if you have any question or issue with this!
Andrea

**Comment by karinapriajina** [comment]
Hi @andreafalzetti ! Thank you! I see there's 6 russian topics with titles only, is that you?
I don't think Viktor has started yet, which reminds me I have to prompt him, but if there are any issues I will let you know. Many thanks again!!!!

Best,

Karina

**Comment by andreafalzetti** [comment]
Hi @karinapriajina, yes it was me. I have translated them so I could help you setting the right icon!

Have fun :)

**Comment by karinapriajina** [comment]
Thanks a lot Andrea! I have another question: for some reason when I go to a Russian language topic and click on "view topic" I can't view it. The homepage appears so I have no idea what the Russian text looks like on the front end. I there a way for me to see the Russian front-end?

**Comment by karinapriajina** [comment]
This has been resolved. Thanks
