### ISSUE TITLE
Ukrainian Translation Publications

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#84]
Hello there lovely people! I have a small issue. Either I forgot how to do this or it has changed: I was trying to translate into Ukrainian a publication I have just uploaded and usually when I click here (the ukrainian flag next to the publication name, which is now "Uploading"): 
![image](https://user-images.githubusercontent.com/15872221/28661248-573d0cac-72b6-11e7-9748-18e5b140471d.png)

It opens up a "publication window and I simply duplicate the content, but now, it brings me here instead:

![image](https://user-images.githubusercontent.com/15872221/28661316-8f3182b4-72b6-11e7-9f5e-c6b244142b9d.png)

So, what am I doing wrong here?

Thanks a lot!

Kind regards,

Karina

**Comment by andreafalzetti** [comment]
@karinapriajina I think if you just use the tools internal to the publication (to the right-hand side) it will duplicate the publication and you can use the normal interface. If you translate the item using the link in the flag, it will trigger this interface.

**Comment by karinapriajina** [comment]
Thanks Andrea. I found a semi-weird way to duplicate the content except for pdf files, which I then uploaded again.
