### ISSUE TITLE
Taxonomy Russian

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#86]
Dear all,

Viktor tells me he's getting close to completing everything. How are we doing on the translation of elements he cannot touch? You do have the documents for that haven't you? Also, I have no idea what the russian front end is looking like... can't see it :(

**Comment by karinapriajina** [comment]
I can now see the Russian front-end which looks messy.

**Comment by karinapriajina** [comment]
There is a problem with the menu synchronisation, the full menu is not displayed in Russian. 
In some Topics and Actors, when you go into the back end, half of the info is filled in in one language and half in another, true for all languages.

Examples: 
http://ukrainesecuritysector.com/wp-admin/term.php?taxonomy=actors&tag_ID=161&post_type=publication&wp_http_referer=%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dactors%26post_type%3Dpublication   UKR/ENG problem--> it appear in ukranian while the overall language of the page is english

http://ukrainesecuritysector.com/wp-admin/term.php?taxonomy=topic&tag_ID=188&post_type=publication&wp_http_referer=%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dtopic%26post_type%3Dpublication%26paged%3D2&lang=ru&admin_bar=1

RUS/UKR problem --> the russian text doesn't appear although Viktor has repeatedly put it in.

**Comment by karinapriajina** [comment]
Hi there! How are we doing on the russian version of this site?

Best,

Karina

**Comment by bhavesh-activatemedia** [comment]
Hi @karinapriajina Andrea isn't in today. He's back in the office next week so he'll take a look at this then.

**Comment by andreafalzetti** [comment]
Regarding the first issue, about the term "Рада Національної Безпеки" I don't understand what is the issue? The tag is in UKR. Shall it be RU instead?

**Comment by andreafalzetti** [comment]
Regarding the second issue, what text is Viktor loading and in which field?

**Comment by karinapriajina** [comment]
Hi Andrea! For the first issue I just sent you a screen grab.
For the second, persumably Viktor has filled it in as he has done for the rest of the pages , but it doesn't appear apparently. He's now on holiday so I can't get him to try again. Let me see if I can try myself

**Comment by karinapriajina** [comment]
Seems to work now (the second issue)

**Comment by andreafalzetti** [comment]
ok, great! Even if I haven't changed anything, good to head it works now. Regarding the first issue, the language for the tag is handled from the dropdown below the content. I don't see any specific issue regarding the language! 

![ukrainesecuritysector com-wp-admin-term php-taxonomy actors tag_id 161 post_type publication wp_http_referer 2fwp-admin 2fedit-tags php 3ftaxonomy 3dactors 26post_type 3dpublication 1](https://user-images.githubusercontent.com/2318450/29824782-5610f252-8cca-11e7-9b0f-576e352b92b3.png)
