### ISSUE TITLE
add sharing plugin

### ISSUE THREAD

**Issue by adrian-activate** [ActivateMedia/DCAF-Ukraine#9]
plugin to share site/articles on social media

**Comment by andreafalzetti** [comment]
I've installed the WordPress plugin [Easy Social Share Buttons
](https://wordpress.org/plugins/easy-social-share-buttons/)

**How to use it**

```
[ess_post]
[ess_post share_type="count"]
[ess_post share_type="text"]
<?php echo do_shortcode( '[ess_post]' ); ?>
```

Settings page:
http://dcaf-ua.activatemedia.com/wp-admin/options-general.php?page=easy_social_share_buttons_settings
