### ISSUE TITLE
visual differences between languages in Events, News, Homepage, (all posts- colours and icons)

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#90]
ENG
![image](https://user-images.githubusercontent.com/15872221/33429398-fd307fda-d5cc-11e7-9b71-0e7accf5865a.png)

UK/RU

![image](https://user-images.githubusercontent.com/15872221/33429409-0981d45a-d5cd-11e7-8fc3-c48d80e29cd6.png)

**Comment by gianpaolom** [comment]
@karinapriajina 
I have looked into it for both RU and UK language and now the icons and colours should be consistent with the behaviour of EN page. On UK page there are two posts without icon, as they are in `gallery` category, which does not have an icon defined.
Please check and let me know if any issue.
